services:
  portfolio:
    image: jekyll/jekyll:latest
    container_name: portfolio
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --watch --force_polling --livereload --host 0.0.0.0 --port 4000
    environment:
      - JEKYLL_ENV=development
    restart: unless-stopped

